version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - run: sudo apt -y install cmake libboost-system-dev libboost-program-options-dev libssl-dev default-libmysqlclient-dev
      - run: cmake -DCMAKE_INSTALL_PREFIX=/usr -DSYSTEMD_SERVICE=ON .
      - run: sudo make install -j2
      - run: ./trojan -v
      - run: sudo ctest
